kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ include "gocdb.fullname" . }}
  labels:
    {{- include "gocdb.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "gocdb.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gocdb.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "gocdb.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          env:
            - name: GOCDB_API_KEY
              value: "{{ .Values.apiKey | default (randAlphaNum 12) }}"
            - name: SITEACC_API
              value: "{{ required "The site accounts API must be set" .Values.siteaccApi }}"
            - name: DATABASE_SERVER
              value: "{{ include "gocdb.fullname" . }}-{{ .Values.database.nameOverride }}"
            - name: DATABASE_PORT
              value: "{{ .Values.database.primary.service.port }}"
            - name: DATABASE_USER_NAME
              value: "{{ .Values.database.gocdbUser.name }}"
            - name: DATABASE_USER_PASSWORD
              value: "{{ .Values.database.gocdbUser.password }}"
            {{- range $name, $value := .Values.env }}
            - name: "{{ $name }}"
              value: "{{ $value }}"
            {{- end }}
          volumeMounts:
            - mountPath: /var/www/html/.htaccess
              subPath: htaccess
              name: config
            - mountPath: /var/www/html/gocdb/config/local_info.xml
              subPath: local_info.xml
              name: config
      restartPolicy: Always
      volumes:
        - name: config
          configMap:
            name: {{ include "gocdb.fullname" . }}-config
