url: "https://sciencemesh-test.uni-muenster.de/testdb"
defaultScope: "SM"
apiKey: "test123"
siteaccApi: "https://sciencemesh-test.uni-muenster.de/api/siteacc"

ingress:
  enabled: true
  path: /testdb
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/rewrite-target: /

database:
  global:
    storageClass: cephfs
